import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Layout } from '@/components/layout/Layout';
import { useAuthStore } from '@/stores/authStore';
import { 
  Activity, 
  Dumbbell, 
  UtensilsCrossed, 
  TrendingUp,
  Brain,
  Target,
  Zap,
  ChevronRight,
  Check,
  Sparkles
} from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Plans',
    description: 'Personalized workout and meal plans generated by advanced AI based on your goals.',
  },
  {
    icon: Dumbbell,
    title: 'Custom Workouts',
    description: 'Home, gym, or outdoor workouts tailored to your fitness level and time.',
  },
  {
    icon: UtensilsCrossed,
    title: 'Smart Meal Planning',
    description: 'Complete daily meal plans with exact timings, calories, and macros.',
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Visual charts and summaries to track your fitness journey.',
  },
  {
    icon: Target,
    title: 'Health Calculators',
    description: 'BMI, BMR, calorie requirements, and ideal weight calculations.',
  },
  {
    icon: Zap,
    title: 'Exercise Library',
    description: 'Extensive database with videos, form tips, and muscle targeting.',
  },
];

const goals = [
  { goal: 'Weight Loss', icon: '🔥' },
  { goal: 'Muscle Gain', icon: '💪' },
  { goal: 'Endurance', icon: '🏃' },
  { goal: 'Flexibility', icon: '🧘' },
  { goal: 'General Fitness', icon: '⚡' },
];

export default function Index() {
  const { user } = useAuthStore();

  return (
    <Layout>
      {/* Hero Section */}
      <section className="relative overflow-hidden min-h-[90vh] flex items-center">
        {/* Background */}
        <div className="absolute inset-0 gradient-hero" />
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-20 left-1/4 w-[500px] h-[500px] bg-primary/20 rounded-full blur-[120px] animate-pulse-slow" />
          <div className="absolute bottom-20 right-1/4 w-[400px] h-[400px] bg-accent/15 rounded-full blur-[100px] animate-pulse-slow" style={{ animationDelay: '2s' }} />
        </div>

        <div className="container mx-auto px-4 py-20 relative z-10">
          <div className="max-w-4xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-8 animate-fade-in">
              <Sparkles className="w-4 h-4 text-primary" />
              <span className="text-sm font-medium text-primary">AI-Powered Fitness Revolution</span>
            </div>
            
            <h1 className="font-display text-4xl md:text-6xl lg:text-7xl font-bold mb-6 animate-fade-in-up leading-tight" style={{ animationDelay: '0.1s' }}>
              Transform Your Health with{' '}
              <span className="text-gradient-primary">Intelligent</span>{' '}
              Fitness Planning
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
              Get personalized workout routines, AI-generated meal plans, and comprehensive health tracking 
              – all tailored to your unique goals and lifestyle.
            </p>
            
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-fade-in-up" style={{ animationDelay: '0.3s' }}>
              {user ? (
                <Link to="/dashboard">
                  <Button variant="gradient" size="xl" className="group">
                    Go to Dashboard
                    <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </Link>
              ) : (
                <>
                  <Link to="/auth?mode=signup">
                    <Button variant="gradient" size="xl" className="group">
                      Start Your Journey
                      <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                    </Button>
                  </Link>
                  <Link to="/auth">
                    <Button variant="outline" size="xl" className="border-border/50 hover:bg-secondary/50">
                      Sign In
                    </Button>
                  </Link>
                </>
              )}
            </div>

            {/* Goal Pills */}
            <div className="flex flex-wrap items-center justify-center gap-3 mt-16 animate-fade-in-up" style={{ animationDelay: '0.4s' }}>
              {goals.map((item) => (
                <div 
                  key={item.goal}
                  className="flex items-center gap-2 px-4 py-2 rounded-full bg-secondary/50 border border-border/50 hover:bg-secondary/80 transition-colors cursor-default"
                >
                  <span>{item.icon}</span>
                  <span className="text-sm font-medium">{item.goal}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-background">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-4">
              Everything You Need to{' '}
              <span className="text-gradient-primary">Succeed</span>
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Comprehensive tools and AI-powered features to help you achieve your fitness goals faster.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <div 
                key={feature.title}
                className="group p-6 rounded-2xl bg-card border border-border hover:border-primary/30 transition-all duration-300 hover:shadow-lg hover:shadow-primary/5 animate-fade-in-up"
                style={{ animationDelay: `${0.1 * index}s` }}
              >
                <div className="w-12 h-12 rounded-xl gradient-primary flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                  <feature.icon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="font-display text-xl font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24">
        <div className="container mx-auto px-4">
          <div className="relative rounded-3xl overflow-hidden">
            <div className="absolute inset-0 gradient-primary" />
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_50%,rgba(255,255,255,0.1),transparent_50%)]" />
            
            <div className="relative z-10 py-16 px-8 md:py-24 md:px-16 text-center">
              <h2 className="font-display text-3xl md:text-5xl font-bold text-primary-foreground mb-6">
                Ready to Transform Your Life?
              </h2>
              <p className="text-primary-foreground/80 text-lg mb-8 max-w-2xl mx-auto">
                Join thousands who have achieved their fitness goals with our AI-powered platform.
              </p>
              
              {!user && (
                <Link to="/auth?mode=signup">
                  <Button 
                    size="xl" 
                    className="bg-background text-foreground hover:bg-background/90 shadow-lg"
                  >
                    Get Started Free
                    <ChevronRight className="w-5 h-5 ml-2" />
                  </Button>
                </Link>
              )}

              <div className="flex flex-wrap items-center justify-center gap-6 mt-10 text-primary-foreground/90">
                {['Free to start', 'No credit card required', 'Cancel anytime'].map((item) => (
                  <div key={item} className="flex items-center gap-2">
                    <Check className="w-5 h-5" />
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 border-t border-border">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg gradient-primary flex items-center justify-center">
                <Activity className="w-4 h-4 text-primary-foreground" />
              </div>
              <span className="font-display font-bold text-lg">FitAI</span>
            </div>
            <p className="text-sm text-muted-foreground">
              © 2024 FitAI. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </Layout>
  );
}
