import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Layout } from '@/components/layout/Layout';
import { useAuthStore } from '@/stores/authStore';
import { 
  Activity, 
  Dumbbell, 
  UtensilsCrossed, 
  TrendingUp,
  Brain,
  Target,
  Zap,
  ChevronRight,
  Check
} from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Plans',
    description: 'Personalized workout and meal plans generated by advanced AI based on your goals and preferences.',
  },
  {
    icon: Dumbbell,
    title: 'Custom Workouts',
    description: 'Home, gym, or outdoor workouts tailored to your fitness level and available time.',
  },
  {
    icon: UtensilsCrossed,
    title: 'Smart Meal Planning',
    description: 'Complete daily meal plans with exact timings, calories, and macros for your goals.',
  },
  {
    icon: TrendingUp,
    title: 'Progress Tracking',
    description: 'Visual charts and summaries to track your weight, workouts, and meal adherence.',
  },
  {
    icon: Target,
    title: 'Health Calculators',
    description: 'BMI, BMR, calorie requirements, and ideal weight calculations with visual indicators.',
  },
  {
    icon: Zap,
    title: 'Exercise Library',
    description: 'Extensive exercise database with videos, form tips, and muscle targeting info.',
  },
];

const plans = [
  { goal: 'Weight Loss', icon: '🔥' },
  { goal: 'Muscle Gain', icon: '💪' },
  { goal: 'Endurance', icon: '🏃' },
  { goal: 'Flexibility', icon: '🧘' },
  { goal: 'General Fitness', icon: '⚡' },
];

export default function Index() {
  const { user } = useAuthStore();

  return (
    <Layout>
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl animate-pulse-slow" />
          <div className="absolute bottom-1/4 right-1/4 w-80 h-80 bg-accent/20 rounded-full blur-3xl animate-pulse-slow" style={{ animationDelay: '2s' }} />
        </div>

        <div className="container mx-auto px-4 py-20 md:py-32 relative z-10">
          <div className="max-w-4xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-8 animate-fade-in">
              <Activity className="w-4 h-4 text-primary" />
              <span className="text-sm text-muted-foreground">AI-Powered Fitness Revolution</span>
            </div>
            
            <h1 className="font-display text-4xl md:text-6xl lg:text-7xl font-bold mb-6 animate-fade-in-up" style={{ animationDelay: '0.1s' }}>
              Transform Your Health with{' '}
              <span className="text-gradient">Intelligent</span>{' '}
              Fitness Planning
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
              Get personalized workout routines, AI-generated meal plans, and comprehensive health tracking 
              – all tailored to your unique goals and lifestyle.
            </p>
            
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-fade-in-up" style={{ animationDelay: '0.3s' }}>
              {user ? (
                <Link to="/dashboard">
                  <Button variant="gradient" size="xl" className="group">
                    Go to Dashboard
                    <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </Link>
              ) : (
                <>
                  <Link to="/auth?mode=signup">
                    <Button variant="gradient" size="xl" className="group">
                      Start Your Journey
                      <ChevronRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                    </Button>
                  </Link>
                  <Link to="/auth">
                    <Button variant="glass" size="xl">
                      Sign In
                    </Button>
                  </Link>
                </>
              )}
            </div>
          </div>

          {/* Goal Pills */}
          <div className="flex flex-wrap items-center justify-center gap-3 mt-16 animate-fade-in-up" style={{ animationDelay: '0.4s' }}>
            {plans.map((plan) => (
              <div 
                key={plan.goal}
                className="flex items-center gap-2 px-4 py-2 rounded-full glass hover:bg-card/90 transition-colors cursor-default"
              >
                <span>{plan.icon}</span>
                <span className="text-sm font-medium">{plan.goal}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 md:py-32">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="font-display text-3xl md:text-4xl font-bold mb-4">
              Everything You Need to{' '}
              <span className="text-gradient">Succeed</span>
            </h2>
            <p className="text-muted-foreground max-w-2xl mx-auto">
              Comprehensive tools and AI-powered features to help you achieve your fitness goals faster.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <div 
                key={feature.title}
                className="group p-6 rounded-2xl glass hover:bg-card/90 transition-all duration-300 hover:scale-[1.02] animate-fade-in-up"
                style={{ animationDelay: `${0.1 * index}s` }}
              >
                <div className="w-12 h-12 rounded-xl gradient-primary flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                  <feature.icon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="font-display text-xl font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 md:py-32">
        <div className="container mx-auto px-4">
          <div className="relative rounded-3xl overflow-hidden">
            <div className="absolute inset-0 gradient-primary opacity-90" />
            <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxnIGZpbGw9IiNmZmYiIGZpbGwtb3BhY2l0eT0iMC4xIj48cGF0aCBkPSJNMzYgMzRjMC0yLjIxLTEuNzktNC00LTRzLTQgMS43OS00IDQgMS43OSA0IDQgNCA0LTEuNzkgNC00eiIvPjwvZz48L2c+PC9zdmc+')] opacity-30" />
            
            <div className="relative z-10 py-16 px-8 md:py-24 md:px-16 text-center">
              <h2 className="font-display text-3xl md:text-5xl font-bold text-primary-foreground mb-6">
                Ready to Transform Your Life?
              </h2>
              <p className="text-primary-foreground/80 text-lg mb-8 max-w-2xl mx-auto">
                Join thousands of users who have achieved their fitness goals with our AI-powered platform.
              </p>
              
              <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                {!user && (
                  <Link to="/auth?mode=signup">
                    <Button 
                      variant="outline" 
                      size="xl" 
                      className="bg-primary-foreground text-primary hover:bg-primary-foreground/90 border-0"
                    >
                      Get Started Free
                    </Button>
                  </Link>
                )}
              </div>

              <div className="flex flex-wrap items-center justify-center gap-6 mt-10 text-primary-foreground/80">
                {['Free to start', 'No credit card required', 'Cancel anytime'].map((item) => (
                  <div key={item} className="flex items-center gap-2">
                    <Check className="w-5 h-5" />
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 border-t border-border/50">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg gradient-primary flex items-center justify-center">
                <Activity className="w-4 h-4 text-primary-foreground" />
              </div>
              <span className="font-display font-bold">FitAI</span>
            </div>
            <p className="text-sm text-muted-foreground">
              © 2024 FitAI. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </Layout>
  );
}
