-- ============================================================================
-- DailyLift — seed the shared exercise library (38 global exercises).
-- Idempotent: keyed on the unique slug, ON CONFLICT DO NOTHING. Safe to re-run
-- and safe on a fresh database. created_by is NULL => these are global rows
-- visible to everyone via the existing "view global or own exercises" policy.
-- Does not touch or overwrite user-created custom exercises.
-- ============================================================================

INSERT INTO public.exercises
  (slug, name, primary_muscle, secondary_muscles, equipment, exercise_type, movement_pattern, difficulty, environment, instructions, common_mistakes, safety_notes, is_unilateral)
VALUES
  ('barbell-bench-press', 'Barbell Bench Press', 'chest', ARRAY['triceps','shoulders']::text[], 'barbell', 'compound', 'push', 'intermediate', 'gym', ARRAY['Lie flat on the bench with feet planted and eyes under the bar.','Grip slightly wider than shoulder width and unrack the bar.','Lower the bar to mid-chest with elbows about 45 degrees.','Press back up until arms are extended without locking out hard.']::text[], ARRAY['Flaring elbows to 90 degrees','Bouncing the bar off the chest','Lifting hips off the bench']::text[], 'Use a spotter or safety pins when training near failure.', FALSE),
  ('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', ARRAY['shoulders','triceps']::text[], 'dumbbell', 'compound', 'push', 'beginner', 'gym', ARRAY['Set the bench to about 30 degrees.','Press dumbbells up from shoulder level until arms are extended.','Lower under control until you feel a stretch across the upper chest.']::text[], ARRAY['Setting the incline too steep','Clashing the dumbbells at the top']::text[], NULL, FALSE),
  ('push-up', 'Push-Up', 'chest', ARRAY['triceps','shoulders','core']::text[], 'bodyweight', 'compound', 'push', 'beginner', 'both', ARRAY['Start in a plank with hands slightly wider than shoulders.','Keep a straight line from head to heels and brace your core.','Lower until your chest is just above the floor, then press back up.']::text[], ARRAY['Sagging hips','Flaring elbows wide','Partial range of motion']::text[], NULL, FALSE),
  ('cable-fly', 'Cable Chest Fly', 'chest', ARRAY['shoulders']::text[], 'cable', 'isolation', 'push', 'beginner', 'gym', ARRAY['Set cables to chest height and take a staggered stance.','With a slight elbow bend, bring the handles together in front of you.','Control the return until you feel a stretch across the chest.']::text[], ARRAY['Turning it into a press','Using too much weight and losing the stretch']::text[], NULL, FALSE),
  ('pull-up', 'Pull-Up', 'back', ARRAY['biceps','core']::text[], 'bodyweight', 'compound', 'pull', 'intermediate', 'both', ARRAY['Hang from a bar with an overhand grip slightly wider than shoulders.','Pull your chest toward the bar by driving elbows down.','Lower under control to a full hang.']::text[], ARRAY['Kipping unintentionally','Not reaching full extension at the bottom']::text[], NULL, FALSE),
  ('lat-pulldown', 'Lat Pulldown', 'back', ARRAY['biceps']::text[], 'cable', 'compound', 'pull', 'beginner', 'gym', ARRAY['Grip the bar wider than shoulder width and sit with thighs secured.','Pull the bar to your upper chest, leading with the elbows.','Control the bar back up to a full stretch.']::text[], ARRAY['Leaning back excessively','Pulling behind the neck']::text[], NULL, FALSE),
  ('bent-over-barbell-row', 'Bent-Over Barbell Row', 'back', ARRAY['biceps','hamstrings']::text[], 'barbell', 'compound', 'pull', 'intermediate', 'gym', ARRAY['Hinge at the hips with a flat back and soft knees.','Row the bar to your lower ribs, squeezing the shoulder blades.','Lower under control without rounding the back.']::text[], ARRAY['Rounding the lower back','Using momentum to heave the weight']::text[], 'Keep the load moderate to protect a neutral spine.', FALSE),
  ('seated-cable-row', 'Seated Cable Row', 'back', ARRAY['biceps']::text[], 'cable', 'compound', 'pull', 'beginner', 'gym', ARRAY['Sit tall with a slight lean and grab the handle.','Pull to your stomach, driving the elbows back.','Return under control to a full stretch.']::text[], ARRAY['Excessive back swing','Shrugging the shoulders']::text[], NULL, FALSE),
  ('overhead-press', 'Overhead Press', 'shoulders', ARRAY['triceps','core']::text[], 'barbell', 'compound', 'push', 'intermediate', 'gym', ARRAY['Hold the bar at shoulder height with hands just outside shoulders.','Brace your core and press overhead, moving your head back then through.','Lock out overhead, then lower under control.']::text[], ARRAY['Excessive lower-back arch','Pressing the bar around the face']::text[], 'Brace hard and avoid leaning back to protect the lower back.', FALSE),
  ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'shoulders', ARRAY[]::text[], 'dumbbell', 'isolation', 'push', 'beginner', 'both', ARRAY['Stand with dumbbells at your sides, elbows slightly bent.','Raise the weights out to the sides to about shoulder height.','Lower slowly under control.']::text[], ARRAY['Using momentum','Shrugging the traps','Going far above shoulder height']::text[], NULL, FALSE),
  ('face-pull', 'Face Pull', 'shoulders', ARRAY['back']::text[], 'cable', 'isolation', 'pull', 'beginner', 'gym', ARRAY['Set a rope at upper-chest height.','Pull the rope toward your face, splitting it apart as you go.','Control the return.']::text[], ARRAY['Using too much weight','Letting the elbows drop']::text[], NULL, FALSE),
  ('barbell-curl', 'Barbell Biceps Curl', 'biceps', ARRAY['forearms']::text[], 'barbell', 'isolation', 'pull', 'beginner', 'gym', ARRAY['Hold the bar with an underhand shoulder-width grip.','Curl the bar up by flexing the elbows, keeping them at your sides.','Lower under control to full extension.']::text[], ARRAY['Swinging the torso','Letting elbows drift forward']::text[], NULL, FALSE),
  ('dumbbell-hammer-curl', 'Dumbbell Hammer Curl', 'biceps', ARRAY['forearms']::text[], 'dumbbell', 'isolation', 'pull', 'beginner', 'both', ARRAY['Hold dumbbells with a neutral (palms-facing) grip.','Curl up while keeping the wrists neutral.','Lower under control.']::text[], ARRAY['Swinging','Partial range of motion']::text[], NULL, FALSE),
  ('triceps-pushdown', 'Triceps Rope Pushdown', 'triceps', ARRAY[]::text[], 'cable', 'isolation', 'push', 'beginner', 'gym', ARRAY['Attach a rope to a high pulley and grab it with a neutral grip.','Keep elbows pinned and extend down, spreading the rope at the bottom.','Control the return to about 90 degrees.']::text[], ARRAY['Letting elbows flare and drift','Using the shoulders']::text[], NULL, FALSE),
  ('overhead-dumbbell-extension', 'Overhead Dumbbell Triceps Extension', 'triceps', ARRAY[]::text[], 'dumbbell', 'isolation', 'push', 'beginner', 'both', ARRAY['Hold one dumbbell overhead with both hands.','Lower behind your head by bending the elbows.','Extend back overhead under control.']::text[], ARRAY['Flaring elbows wide','Arching the lower back']::text[], NULL, FALSE),
  ('barbell-back-squat', 'Barbell Back Squat', 'quads', ARRAY['glutes','hamstrings','core']::text[], 'barbell', 'compound', 'squat', 'intermediate', 'gym', ARRAY['Set the bar on your upper back and stand with feet shoulder-width.','Brace, then sit down and back until thighs are at least parallel.','Drive up through mid-foot to standing.']::text[], ARRAY['Knees caving in','Heels lifting','Rounding the lower back']::text[], 'Squat inside a rack with safety pins set below depth.', FALSE),
  ('goblet-squat', 'Goblet Squat', 'quads', ARRAY['glutes','core']::text[], 'dumbbell', 'compound', 'squat', 'beginner', 'both', ARRAY['Hold a dumbbell or kettlebell at chest height.','Squat down keeping your torso upright and elbows inside the knees.','Drive back up to standing.']::text[], ARRAY['Rounding forward','Heels rising']::text[], NULL, FALSE),
  ('leg-press', 'Leg Press', 'quads', ARRAY['glutes','hamstrings']::text[], 'machine', 'compound', 'squat', 'beginner', 'gym', ARRAY['Sit in the machine with feet shoulder-width on the platform.','Lower the platform until knees reach about 90 degrees.','Press back without locking the knees hard.']::text[], ARRAY['Letting the lower back round at the bottom','Locking knees aggressively']::text[], 'Do not let the knees collapse inward under load.', FALSE),
  ('romanian-deadlift', 'Romanian Deadlift', 'hamstrings', ARRAY['glutes','back']::text[], 'barbell', 'compound', 'hinge', 'intermediate', 'gym', ARRAY['Hold the bar at your thighs with a flat back.','Push the hips back, lowering the bar along your legs until you feel a hamstring stretch.','Drive the hips forward to stand tall.']::text[], ARRAY['Rounding the back','Turning it into a squat','Bar drifting away from the legs']::text[], 'Keep the bar close and stop when the back would otherwise round.', FALSE),
  ('lying-leg-curl', 'Lying Leg Curl', 'hamstrings', ARRAY['calves']::text[], 'machine', 'isolation', 'hinge', 'beginner', 'gym', ARRAY['Lie face down with the pad above your heels.','Curl your heels toward your glutes.','Lower under control.']::text[], ARRAY['Lifting hips off the pad','Using momentum']::text[], NULL, FALSE),
  ('conventional-deadlift', 'Conventional Deadlift', 'back', ARRAY['glutes','hamstrings','core']::text[], 'barbell', 'compound', 'hinge', 'advanced', 'gym', ARRAY['Set up with the bar over mid-foot and shins close.','Grip the bar, brace, and take the slack out.','Drive the floor away and stand tall, then lower with control.']::text[], ARRAY['Rounding the back','Jerking the bar off the floor','Hips shooting up first']::text[], 'Prioritize a braced, neutral spine over load.', FALSE),
  ('hip-thrust', 'Barbell Hip Thrust', 'glutes', ARRAY['hamstrings']::text[], 'barbell', 'compound', 'hinge', 'beginner', 'gym', ARRAY['Sit with your upper back against a bench and the bar over your hips.','Drive through your heels to lift the hips until the torso is parallel to the floor.','Squeeze the glutes at the top, then lower under control.']::text[], ARRAY['Overextending the lower back','Pushing through the toes']::text[], 'Use a pad and avoid hyperextending at the top.', FALSE),
  ('walking-lunge', 'Walking Lunge', 'quads', ARRAY['glutes','hamstrings']::text[], 'dumbbell', 'compound', 'lunge', 'beginner', 'both', ARRAY['Hold dumbbells at your sides.','Step forward and lower until both knees are about 90 degrees.','Drive through the front heel and step into the next lunge.']::text[], ARRAY['Front knee caving in','Short, unstable steps']::text[], NULL, TRUE),
  ('standing-calf-raise', 'Standing Calf Raise', 'calves', ARRAY[]::text[], 'machine', 'isolation', 'push', 'beginner', 'both', ARRAY['Stand with the balls of your feet on a raised surface.','Rise onto your toes as high as possible.','Lower slowly for a full stretch.']::text[], ARRAY['Bouncing','Partial range of motion']::text[], NULL, FALSE),
  ('plank', 'Plank', 'core', ARRAY['shoulders']::text[], 'bodyweight', 'isolation', 'core', 'beginner', 'both', ARRAY['Rest on your forearms and toes with a straight body line.','Brace your core and squeeze your glutes.','Hold for the target time without sagging.']::text[], ARRAY['Hips sagging or piking up','Holding your breath']::text[], NULL, FALSE),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'core', ARRAY['hip flexors']::text[], 'bodyweight', 'isolation', 'core', 'intermediate', 'both', ARRAY['Hang from a bar with a controlled grip.','Raise your legs to about hip height or higher, keeping them straight.','Lower under control without swinging.']::text[], ARRAY['Swinging for momentum','Using only the hip flexors']::text[], NULL, FALSE),
  ('cable-crunch', 'Cable Crunch', 'core', ARRAY[]::text[], 'cable', 'isolation', 'core', 'beginner', 'gym', ARRAY['Kneel below a rope attachment and hold it by your head.','Crunch down by flexing the spine, bringing elbows toward the thighs.','Return under control.']::text[], ARRAY['Pulling with the arms','Hinging at the hips instead of crunching']::text[], NULL, FALSE),
  ('treadmill-run', 'Treadmill Run', 'cardio', ARRAY['quads','calves']::text[], 'machine', 'cardio', 'cardio', 'beginner', 'gym', ARRAY['Set a comfortable pace and incline.','Maintain an upright posture and relaxed arms.','Keep to your target duration or distance.']::text[], ARRAY['Holding the handrails','Overstriding']::text[], NULL, FALSE),
  ('jump-rope', 'Jump Rope', 'cardio', ARRAY['calves','shoulders']::text[], 'other', 'cardio', 'cardio', 'beginner', 'both', ARRAY['Turn the rope with your wrists, not your arms.','Jump just high enough to clear the rope.','Land softly on the balls of your feet.']::text[], ARRAY['Jumping too high','Swinging from the shoulders']::text[], NULL, FALSE),
  ('burpee', 'Burpee', 'cardio', ARRAY['chest','quads','core']::text[], 'bodyweight', 'cardio', 'cardio', 'intermediate', 'both', ARRAY['From standing, drop into a squat and place your hands down.','Kick your feet back to a plank and perform a push-up.','Return your feet and jump up explosively.']::text[], ARRAY['Sagging hips in the plank','Skipping the push-up depth']::text[], NULL, FALSE),
  ('mountain-climber', 'Mountain Climber', 'core', ARRAY['shoulders','quads']::text[], 'bodyweight', 'cardio', 'core', 'beginner', 'both', ARRAY['Start in a strong plank position.','Drive one knee toward your chest, then switch quickly.','Keep your hips low and core braced throughout.']::text[], ARRAY['Hips rising too high','Losing the plank line']::text[], NULL, TRUE),
  ('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'shoulders', ARRAY['triceps']::text[], 'dumbbell', 'compound', 'push', 'beginner', 'both', ARRAY['Sit or stand with dumbbells at shoulder height.','Press overhead until arms are extended.','Lower under control to the starting position.']::text[], ARRAY['Arching the lower back','Pressing the weights forward instead of up']::text[], NULL, FALSE),
  ('chin-up', 'Chin-Up', 'back', ARRAY['biceps']::text[], 'bodyweight', 'compound', 'pull', 'intermediate', 'both', ARRAY['Hang from a bar with an underhand shoulder-width grip.','Pull until your chin clears the bar.','Lower under control to a full hang.']::text[], ARRAY['Not reaching full extension','Kipping']::text[], NULL, FALSE),
  ('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hamstrings', ARRAY['glutes','back']::text[], 'dumbbell', 'compound', 'hinge', 'beginner', 'both', ARRAY['Hold dumbbells in front of your thighs.','Hinge at the hips, lowering the weights along your legs.','Drive the hips forward to stand tall.']::text[], ARRAY['Rounding the back','Bending the knees too much']::text[], 'Stop the descent before the lower back rounds.', FALSE),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'quads', ARRAY['glutes','hamstrings']::text[], 'dumbbell', 'compound', 'lunge', 'intermediate', 'both', ARRAY['Rest your rear foot on a bench behind you.','Lower straight down until the front thigh is about parallel.','Drive through the front heel to stand.']::text[], ARRAY['Front knee caving','Leaning too far forward']::text[], NULL, TRUE),
  ('glute-bridge', 'Glute Bridge', 'glutes', ARRAY['hamstrings']::text[], 'bodyweight', 'isolation', 'hinge', 'beginner', 'home', ARRAY['Lie on your back with knees bent and feet flat.','Drive through your heels to lift the hips.','Squeeze the glutes at the top, then lower.']::text[], ARRAY['Overarching the lower back','Pushing through the toes']::text[], NULL, FALSE),
  ('machine-chest-press', 'Machine Chest Press', 'chest', ARRAY['triceps','shoulders']::text[], 'machine', 'compound', 'push', 'beginner', 'gym', ARRAY['Adjust the seat so the handles are at mid-chest.','Press the handles forward until arms are extended.','Return under control to a stretch.']::text[], ARRAY['Setting the seat too high or low','Locking out aggressively']::text[], NULL, FALSE),
  ('dumbbell-row', 'Single-Arm Dumbbell Row', 'back', ARRAY['biceps']::text[], 'dumbbell', 'compound', 'pull', 'beginner', 'both', ARRAY['Brace one hand and knee on a bench with a flat back.','Row the dumbbell to your hip, leading with the elbow.','Lower under control to a full stretch.']::text[], ARRAY['Rotating the torso to lift','Shrugging the shoulder']::text[], NULL, TRUE)
ON CONFLICT (slug) DO NOTHING;

NOTIFY pgrst, 'reload schema';
